### ISSUE TITLE
Get motor commands from serial connection

### ISSUE THREAD

**Issue by bpa** [MichaelFQuigley/mousetrapRobotProj#2]
See the following tutorials for ideas:
- https://www.arduino.cc/en/Tutorial/SerialEvent
- https://www.arduino.cc/en/Tutorial/ReadASCIIString
- https://www.arduino.cc/en/Tutorial/SerialCallResponse

**Comment by zufecory** [comment]
I just made an initial commit for the RedBot to receive and execute commands
