### ISSUE TITLE
Define communication api for bot

### ISSUE THREAD

**Issue by bpa** [MichaelFQuigley/mousetrapRobotProj#3]
The two way api will be serial messages.  The serial connection can be treated as binary or text and should be easy to parse with C++ while not requiring libraries that would use too much program space (ATmega328P has 32k).

Possible commands should allow things like:
### For the redbot
- Move forward
- Pivot
- Right wheel 190 (or 75%)
- Left wheel -128 (or -.5)
- Stop (R/L/Both)
- Brake (R/L/B)

_Time components optional_
### For the beaglebone
- Line detected on right
- Line detected on left
- Sonar distance
- Accelerometer readings

**Comment by zufecory** [comment]
Current communication is "{leftWheelSpeed},{rightWheelSpeed}\n" (ex. "255,255\n"), but we can change the separator or end characters very easily if we want to
