### ISSUE TITLE
Generate a 2d map based on mousetrap and wall information

### ISSUE THREAD

**Issue by bpa** [MichaelFQuigley/mousetrapRobotProj#5]
Ideally create a grid of cells that can be marked with wall, mousetrap, or just free vs obstacle.  Could be done before run and saved, or during initialization.  Use resolution in cm<sup>2</sup>

**Comment by MichaelFQuigley** [comment]
Filter the stuff that is not the black surface of the course.

**Comment by zgrogan** [comment]
Done.  Right click on original image to set corners, starting with the top left and go clockwise
