### ISSUE TITLE
Generate shortest path based on map input

### ISSUE THREAD

**Issue by bpa** [MichaelFQuigley/mousetrapRobotProj#7]
The map will consist of a 2d grid of start/end/free/obstructed entries.  See https://en.wikipedia.org/wiki/Motion_planning and https://en.wikipedia.org/wiki/A*_search_algorithm for ideas.
### Required

Require a start position and produce the shortest path to any point in the opposing end zone
### Optional

Find the start point along the initial end zone that produces the shortest path

**Comment by MichaelFQuigley** [comment]
Finished. Extra work may need to be done to enforce that the robot needs to be some distance away from the mousetraps.
